### ISSUE TITLE
Codabench problem

### ISSUE THREAD

**Issue by codenewww** [Junjue-Wang/EarthVQA#19]
Hello, first of all, thank you very much for providing the EarthVQA code. When I upload my 'test.json' test file to Codabench, why is the result automatically displayed on the public leaderboard? Is there any way to delete my submission record, or make my test results visible only to myself?

**Comment by Junjue-Wang** [comment]
I have changed the settings, please update your scores.
---- Replied Message ----
***@***.***>Date9/11/2024 ***@***.***>***@***.***>Subject[Junjue-Wang/EarthVQA] Codabench problem (Issue #19)
Hello, first of all, thank you very much for providing the EarthVQA code. When I upload my 'test.json' test file to Codabench, why is the result automatically displayed on the public leaderboard? Is there any way to delete my submission record, or make my test results visible only to myself?
