### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by Liumouliu** [Junjue-Wang/EarthVQA#2]
Hi,

Thanks for the awesome work.

Would you please share the pretrained weights: 
(log
├── sfpnr50.pth
├── soba.pth)

Best,
liu

**Comment by Junjue-Wang** [comment]
These have been already uploaded to Baidu Drive. Please check.
Besides, the weights are now uploading to Google Drive. It will take some mintues.

**Comment by Liumouliu** [comment]
Thank you very much!
