### ISSUE TITLE
About Codabench

### ISSUE THREAD

**Issue by upup315** [Junjue-Wang/EarthVQA#25]
I apologize for bothering you again. I have noticed that one of my test results on the Codabench platform has been automatically uploaded to the Leaderboard, but I am unable to remove it as it shows that I do not have the necessary permissions. Could you kindly assist in resolving this issue? Thank you very much for your help!

**Comment by Junjue-Wang** [comment]
The best scores are automatically shown on the leaderboard.
But I see your scores show Nan, which is so strange.
