### ISSUE TITLE
from ever.api.preprocess.albu import RandomDiscreteScale

### ISSUE THREAD

**Issue by Peter-blue** [Junjue-Wang/EarthVQA#27]
I download,but I Import  RandomDiscreteScale failure.
pip install ever-beta
pip install git+https://github.com/qubvel/segmentation_models.pytorch
pip install albumentations==1.4.3 # This version is important for our repo.

![image](https://github.com/user-attachments/assets/a9d002c2-14f4-4d06-921d-1a31071ed994)

![image](https://github.com/user-attachments/assets/3420dd38-1491-47f9-b8bb-b596ec158b5d)

**Comment by yuxiaoz** [comment]
Hello, I met the same error, did you solve that? Thanks sincerely.
