### ISSUE TITLE
An error occurred when I run train_soba.sh

### ISSUE THREAD

**Issue by tanshaosuannai** [Junjue-Wang/EarthVQA#29]
![d93d049a-5885-4fe2-a358-1f795a4db2eb](https://github.com/user-attachments/assets/28bca8ec-f05e-4985-97d8-742d62a9b666)

**Comment by Junjue-Wang** [comment]
This may be the wrong version of ablumentation. You could comment out this enhancement.

**Comment by tanshaosuannai** [comment]
> 请问您是否解决了这个问题？我遇到了同样的问题。




I tried every version of ablumentation, but got an error
