### ISSUE TITLE
How to set the pretrain weight in training stage?

### ISSUE THREAD

**Issue by yuxiaoz** [Junjue-Wang/EarthVQA#30]
Hello, when I run train_sfpnr50.sh, haven't found the path for the pretrain weight, how to set that to the train config? Thanks sincerely.

**Comment by Junjue-Wang** [comment]
If you only would like to run sfpnr50, there is no need to set the pretrained weights because ImageNet weights are automatically loaded.

**Comment by yuxiaoz** [comment]
Thanks, if I wanna set the download .pth as the pretrain weight to finetune more datasets, how could I set in the config file?

**Comment by Junjue-Wang** [comment]
For this case, you should refer to other segmentation model fine-tuning project.
