### ISSUE TITLE
Does the dataset is no longer subdivided into Urban and Rural?

### ISSUE THREAD

**Issue by zxsitu** [Junjue-Wang/EarthVQA#5]
Dear authors, thank you for releasing the latest version of the segmented dataset. However, after I downloaded it, I noticed that this dataset is not subdivided into Urban and Rural like “LoveDA”. Therefore, is this dataset in the urban, rural, or mixed category?

**Comment by Junjue-Wang** [comment]
The urban and rural areas are the same as the LoveDA dataset. You can separate according to the indexes on your own.

**Comment by zxsitu** [comment]
@Junjue-Wang Thanks for the clear explanation.
